/*DROP TABLE IF EXISTS CUSTOMER;  
CREATE TABLE CUSTOMER (  
custId LONG AUTO_INCREMENT  PRIMARY KEY,  
name VARCHAR(250) NOT NULL,  
email VARCHAR(100) NOT NULL,  
dob DATE(10) NOT NULL,
mobile VARCHAR(8) NOT NULL,
country VARCHAR(50) NOT NULL
);  

DROP TABLE IF EXISTS ACCOUNT;  
CREATE TABLE ACCOUNT (  
accId LONG AUTO_INCREMENT  PRIMARY KEY,  
status VARCHAR(1) NOT NULL,  
createdOn DATE(10) NOT NULL,  
type VARCHAR(50) NOT NULL,
custId VARCHAR(50) NOT NULL
);  
*/